remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
title: "Bomberman - ProjectCamel"
description: "This project is a tribute to the game Bomberman."

github:
  repository_url: "https://github.com/mxarc"
  repository_url: "https://github.com/JoseTurdeZarandieta"
  repository_url: "https://github.com/Biker13"
